# Generated by Django 5.0 on 2024-01-19 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('in_cart', 'В корзине'), ('processing', 'В обработке'), ('done', 'Исполнен'), ('decline', 'Отменен')], default='in_cart', max_length=20, verbose_name='Статус заказа'),
        ),
    ]
