# Generated by Django 5.0 on 2023-12-25 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='comment',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='summary_calories',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='summary_items',
            field=models.IntegerField(null=True),
        ),
    ]
