# Generated by Django 5.0 on 2024-01-25 07:01

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_status'),
        ('retail', '0002_alter_retailoffice_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='order',
            name='comment',
            field=models.CharField(blank=True, max_length=4000, verbose_name='Комментарий'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время доставки'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='retail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='office', to='retail.retailoffice'),
        ),
    ]
