# Generated by Django 5.0 on 2024-01-19 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RetailOffice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название офиса')),
                ('address', models.TextField(verbose_name='Адрес')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('working_hours', models.CharField(max_length=255, verbose_name='Рабочие часы')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(upload_to='retail_offices/', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Офис продаж',
                'verbose_name_plural': 'Офисы продаж',
            },
        ),
    ]
