# Generated by Django 5.0 on 2024-02-26 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('retail', '0002_alter_retailoffice_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='retailoffice',
            options={'ordering': ['id'], 'verbose_name': 'Офис продаж', 'verbose_name_plural': 'Офисы продаж'},
        ),
    ]
