# Generated by Django 5.0 on 2024-02-26 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ManagerFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя клиента')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=10, null=True, verbose_name='Телефон')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время обращения')),
                ('processed', models.BooleanField(default=False, verbose_name='Обработан')),
            ],
            options={
                'verbose_name': 'Контакт клиента',
                'verbose_name_plural': 'Контакты клиентов',
                'ordering': ['-created_at'],
            },
        ),
    ]
