# Generated by Django 5.0 on 2023-12-16 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crystaluser',
            name='auth_type',
            field=models.CharField(choices=[('phone', 'Phone'), ('mail', 'Mail'), ('google', 'Google'), ('vk', 'VK'), ('psw', 'PSW')], max_length=10),
        ),
    ]
