# Generated by Django 5.0 on 2024-01-26 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0005_crystaluser_is_wholesale_crystaluser_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crystaluser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='email address'),
        ),
    ]
