# Generated by Django 5.0 on 2024-01-20 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('authorization', '0005_crystaluser_is_wholesale_crystaluser_telephone'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='crystaluser',
            constraint=models.UniqueConstraint(condition=models.Q(('auth_type', 'phone')), fields=('auth_type', 'telephone'), name='unique_telephone_for_phone_auth_type'),
        ),
        migrations.AddConstraint(
            model_name='crystaluser',
            constraint=models.UniqueConstraint(condition=models.Q(('auth_type', 'mail')), fields=('auth_type', 'email'), name='unique_email_for_mail_auth_type'),
        ),
    ]
