# Generated by Django 5.0 on 2024-01-26 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('authorization', '0006_alter_crystaluser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crystaluser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='email address'),
        ),
        migrations.AddConstraint(
            model_name='crystaluser',
            constraint=models.UniqueConstraint(fields=('email', 'auth_type'), name='unique_auth_type_email'),
        ),
    ]
