# Generated by Django 5.0 on 2024-01-21 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0006_crystaluser_unique_telephone_for_phone_auth_type_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='crystaluser',
            name='unique_telephone_for_phone_auth_type',
        ),
        migrations.RemoveConstraint(
            model_name='crystaluser',
            name='unique_email_for_mail_auth_type',
        ),
        migrations.RenameField(
            model_name='crystaluser',
            old_name='telephone',
            new_name='phone',
        ),
        migrations.AlterField(
            model_name='crystaluser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, unique=True, verbose_name='email address'),
        ),
    ]
