# Generated by Django 5.0 on 2024-01-26 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0007_alter_crystaluser_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crystaluser',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='email address'),
        ),
    ]
