# Generated by Django 5.0 on 2024-01-27 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0010_crystaluser_birthday_crystaluser_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='crystaluser',
            name='bonus_balance',
            field=models.IntegerField(default=0, verbose_name='Бонусные баллы'),
        ),
    ]
