# Generated by Django 5.0 on 2024-01-28 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0011_crystaluser_bonus_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crystaluser',
            name='is_wholesale',
            field=models.BooleanField(default=False, verbose_name='Оптовик'),
        ),
    ]
