# Generated by Django 5.0 on 2024-03-04 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('authorization', '0012_alter_crystaluser_is_wholesale'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='crystaluser',
            name='unique_auth_type_identifier',
        ),
        migrations.AddField(
            model_name='crystaluser',
            name='yandex_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Yandex ID'),
        ),
        migrations.AlterField(
            model_name='crystaluser',
            name='auth_type',
            field=models.CharField(choices=[('phone', 'По телефону'), ('mail', 'По почте'), ('yandex', 'Yandex'), ('vk', 'VK'), ('password', 'По паролю')], default='password', max_length=10, verbose_name='Тип авторизации'),
        ),
        migrations.AlterField(
            model_name='crystaluser',
            name='email',
            field=models.EmailField(blank=True, default=None, max_length=254, null=True, verbose_name='email address'),
        ),
        migrations.AddConstraint(
            model_name='crystaluser',
            constraint=models.UniqueConstraint(fields=('auth_type', 'email', 'phone', 'username', 'yandex_id'), name='unique_auth_type_identifier'),
        ),
    ]
