# Generated by Django 5.0 on 2024-02-06 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_alter_review_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='text',
            field=models.TextField(max_length=300, verbose_name='Текст отзыва'),
        ),
    ]
