version: '3.3'
services:
  db:
    image: postgres:16-alpine
    volumes:
      - ../.pg_data:/var/lib/postgresql/data/
    env_file:
      - ./.env

  backend:
    image: thrashches/kristall_backend:1.0.0
#    build: ../backend
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ../backend/backend/secret.py:/app/backend/secret.py
      - ../.static:/app/static/
      - ../.media:/app/media/
    depends_on:
      - db
    env_file:
      - ./.env

  frontend:
    image: thrashches/kristall_frontend:1.0.0
    restart: always
    env_file:
      - ./.env

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/var:/var/lib/letsencrypt
      - ../.static:/var/html/static/
      - ../.media:/var/html/media/
      - ./certbot/www:/var/html
    depends_on:
      - backend

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/var:/var/lib/letsencrypt
      - ./certbot/www:/var/html
    depends_on:
      - nginx
    command: certonly --webroot --webroot-path=/var/html --agree-tos --no-eff-email --staging -d dev-crystalcake.tw1.su